name: Build and Push to ACR
on:
  push:
    branches:
      - "main"
      - "feature/cicd-setup"

jobs:
  build:
    name: "Build and Push to ACR"
    runs-on: ubuntu-24.04
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ACR_URL }}
          username: ${{ vars.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.ACR_URL }}/django-job-board:latest
          file: Dockerfile
